### PR TITLE
Merge Android code

### PR DESCRIPTION
**Pull request by moutaigua8183**
There are two commits.
The first one is Android code, but deleting your models in "models" folder, because it failed to download those model files when I cloned the repo.
The second commit is that I manually downloaded those model files and put them into the model folder.

### CODE REVIEW

**Comment by djpetti** [comment]
The merge shouldn't have a problem with the model files not being there, so I'll just merge your first commit and things should be okay.

**Comment by djpetti** [comment]
Something's wrong here. I can't access the actual Android code. When I try to run ```git submodule init``` I get ```fatal: No url found for submodule path 'ISL_Android_Gaze' in .gitmodules``` Did you perhaps forget to commit the .gitmodules file?

**Comment by moutaigua8183** [comment]
It is possible. I am not quite familiar with git, only a few commonly used commands. What i did was cloning your repo, and manual paste my whole working project into the repo, add, commit and push the repo.

**Comment by djpetti** [comment]
Well, somehow it thought is was a submodule... Is your Android project itself a git repository? Instead of copying and pasting the entire thing, can you try manually copying only the relevant files and folders from your project, and then committing that?

Also, don't bother adding in the model files that you couldn't download.

**Comment by djpetti** [comment]
As an alternative, it might be easier if you zipped up your project, posted it to GDrive, and then let me add it in to the repository.

**Comment by moutaigua8183** [comment]
yes, it is a git repository.  Okay, I will zip it up and share it on Gdrive.

**Comment by moutaigua8183** [comment]
It is there, in the Gdrive

**Comment by djpetti** [comment]
Okay, I have manually integrated the android code from the zip file you posted. Thanks.

**Pull request closed without merging**
